# Generated by Django 4.0.5 on 2022-06-08 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_tel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkstationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('computer_name', models.CharField(max_length=100)),
                ('computer_sn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('network', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('ip_address', models.CharField(max_length=3, unique=True)),
                ('peripherals', models.TextField(blank=True)),
                ('roles', models.ManyToManyField(to='core.workstationrole')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('l_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contactperson')),
                ('workstations', models.ManyToManyField(to='core.workstation')),
            ],
        ),
    ]
