# Generated by Django 4.0.5 on 2022-06-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_location', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactperson',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workstation',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workstationrole',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
