# Generated by Django 4.0.5 on 2022-06-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_otherlocation_alter_contactperson_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.workstationrole'),
        ),
    ]
